### ISSUE TITLE
질문 입니다.

### ISSUE THREAD

**Issue by John3210of** [John3210of/springprac#3]
1. 저번에 말씀해 주신 계층에 대해서 나누려고 노력해 보았는데, 맞게 했는지에 대한 확신이 서질 않아서 질문 드립니다.

2.  이번에 서버의 부하를 줄이는 방법중에 캐싱에 대하여 공부해 보았는데, 하루만에 해내는것이 쉽지 않아서 질문 드립니다. 이번 실전 프로젝트 때 이 부분을 꼭 적용해서 하고 싶은데, 구현하면서 도움이 될만한 키워드나 레퍼런스들을 알려주시면 감사하겠습니다! 

https://teamsparta.notion.site/4-a26e486cfe35491a9866000ff7ca35db

api관련 노션페이지 입니다.

**Comment by seongbinko** [comment]
과제 코멘트입니다.
컨트롤러에서 id를 리턴하는 것들도 보이는데, 실전프로젝트에서는 프론트에서 원하는 응답값과http status code를 정하여 리턴하는 것이 필요해보입니다.

1. 코드를 보니 로직상으로 잘 구분하여 나눈 것 같습니다.
2. 스프링 레디스 캐싱으로 검색하셔서 참고해보시면 좋을 것 같습니다. 추가 적으로 서버에 부하를 줄이는 방법은 캐싱뿐만 아니라, 인덱스 설정 및 쿼리 최적화 등도 중요하다고 생각이 듭니다. Jpa에서 퀴리성능 최적화란 키워드로 공부해보시면 도움이 될 것 같습니다.

**Comment by zzangoobrother** [comment]
안녕하세요. 최선강입니다.

한 주 동안 프로젝트 하시느라 수고하셨습니다.

1. 정말 깔끔하게 작성하셨습니다. 이제 한 발 더 나아가 리팩토링도 해보고 oop 적으로 구형해보길 추천합니다. (entity -> dto / dto -> entity 변환은 서비스에서 하는게 좋은 설계일까요?, 중복되는 코드들은 어떻게 하는게 좋을까요? 따로 private 메소드를 만들수도 있고, 클래스를 만들어서 관리 할 수도 있습니다.)

2. 부하가 생기는 여러 원인이 있고, 그 중 하나의 해결이 캐싱입니다. 같은 서버에서 스프링 설정으로 생성한 캐시가 있고, 레디스 캐시, 그리고 aws같은 외부 서버에 레디스 서버를 두는 방법이 있습니다. 서버 내부에 캐시를 만들 때 장점과 외부에 따로 만들어 관리 할 때 장점을 비교해보면 좋습니다.

스프링 캐시
https://mangkyu.tistory.com/179

레디스
https://brunch.co.kr/@skykamja24/575
https://www.youtube.com/watch?v=mPB2CZiAkKM

위 링크 내용 보고 공부하길 추천드립니다.

다음주에도 화이팅하세요!!!
